version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dolphinscheduler
    restart: always

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    restart: always

volumes:
  postgres-data: {}
